gdb_path = "C:\\MinGW\\bin\\gdb.exe"
citra_path = "C:\\Users\\Matthew\\Documents\\Games\\Citra\\nightly\\citra-qt.exe"
oot3d_path = "C:\\Users\\Matthew\\Documents\\Games\\Citra\\Legend of Zelda - Ocarina of Time 3D, The (USA (Rev 1) Decrypted.3ds"

VK_CODE = {'backspace':0x08,
           'tab':0x09,
           'clear':0x0C,
           'enter':0x0D,
           'shift':0x10,
           'ctrl':0x11,
           'alt':0x12,
           'pause':0x13,
           'caps_lock':0x14,
           'esc':0x1B,
           'spacebar':0x20,
           'page_up':0x21,
           'page_down':0x22,
           'end':0x23,
           'home':0x24,
           'left_arrow':0x25,
           'up_arrow':0x26,
           'right_arrow':0x27,
           'down_arrow':0x28,
           'select':0x29,
           'print':0x2A,
           'execute':0x2B,
           'print_screen':0x2C,
           'ins':0x2D,
           'del':0x2E,
           'help':0x2F,
           '0':0x30,
           '1':0x31,
           '2':0x32,
           '3':0x33,
           '4':0x34,
           '5':0x35,
           '6':0x36,
           '7':0x37,
           '8':0x38,
           '9':0x39,
           'a':0x41,
           'b':0x42,
           'c':0x43,
           'd':0x44,
           'e':0x45,
           'f':0x46,
           'g':0x47,
           'h':0x48,
           'i':0x49,
           'j':0x4A,
           'k':0x4B,
           'l':0x4C,
           'm':0x4D,
           'n':0x4E,
           'o':0x4F,
           'p':0x50,
           'q':0x51,
           'r':0x52,
           's':0x53,
           't':0x54,
           'u':0x55,
           'v':0x56,
           'w':0x57,
           'x':0x58,
           'y':0x59,
           'z':0x5A,
           'numpad_0':0x60,
           'numpad_1':0x61,
           'numpad_2':0x62,
           'numpad_3':0x63,
           'numpad_4':0x64,
           'numpad_5':0x65,
           'numpad_6':0x66,
           'numpad_7':0x67,
           'numpad_8':0x68,
           'numpad_9':0x69,
           'multiply_key':0x6A,
           'add_key':0x6B,
           'separator_key':0x6C,
           'subtract_key':0x6D,
           'decimal_key':0x6E,
           'divide_key':0x6F,
           'F1':0x70,
           'F2':0x71,
           'F3':0x72,
           'F4':0x73,
           'F5':0x74,
           'F6':0x75,
           'F7':0x76,
           'F8':0x77,
           'F9':0x78,
           'F10':0x79,
           'F11':0x7A,
           'F12':0x7B,
           'F13':0x7C,
           'F14':0x7D,
           'F15':0x7E,
           'F16':0x7F,
           'F17':0x80,
           'F18':0x81,
           'F19':0x82,
           'F20':0x83,
           'F21':0x84,
           'F22':0x85,
           'F23':0x86,
           'F24':0x87,
           'num_lock':0x90,
           'scroll_lock':0x91,
           'left_shift':0xA0,
           'right_shift ':0xA1,
           'left_control':0xA2,
           'right_control':0xA3,
           'left_menu':0xA4,
           'right_menu':0xA5,
           'browser_back':0xA6,
           'browser_forward':0xA7,
           'browser_refresh':0xA8,
           'browser_stop':0xA9,
           'browser_search':0xAA,
           'browser_favorites':0xAB,
           'browser_start_and_home':0xAC,
           'volume_mute':0xAD,
           'volume_Down':0xAE,
           'volume_up':0xAF,
           'next_track':0xB0,
           'previous_track':0xB1,
           'stop_media':0xB2,
           'play/pause_media':0xB3,
           'start_mail':0xB4,
           'select_media':0xB5,
           'start_application_1':0xB6,
           'start_application_2':0xB7,
           'attn_key':0xF6,
           'crsel_key':0xF7,
           'exsel_key':0xF8,
           'play_key':0xFA,
           'zoom_key':0xFB,
           'clear_key':0xFE,
           '+':0xBB,
           ',':0xBC,
           '-':0xBD,
           '.':0xBE,
           '/':0xBF,
           '`':0xC0,
           ';':0xBA,
           '[':0xDB,
           '\\':0xDC,
           ']':0xDD,
           "'":0xDE,
           '`':0xC0}

actor_names = [
'Player',
'_filler_En_Skeleton_filler_',
'En_Test',
'_filler_En_Iron_filler_',
'En_GirlA',
'_filler_En_Slim_filler_',
'_filler_En_Bskel_filler_',
'En_Part',
'En_Light',
'En_Door',
'En_Box',
'Bg_Dy_Yoseizo',
'Bg_Hidan_Firewall',
'En_Poh',
'En_Okuta',
'Bg_Ydan_Sp',
'En_Bom',
'En_Wallmas',
'En_Dodongo',
'En_Firefly',
'En_Horse',
'En_Item00',
'En_Arrow',
'_filler_Dummy_player_filler_',
'En_Elf',
'En_Niw',
'_filler_En_Bee_filler_',
'En_Tite',
'En_Reeba',
'En_Peehat',
'En_Butte',
'_filler_En_F_Obj_filler_',
'En_Insect',
'En_Fish',
'_filler_En_D_Obj_filler_',
'En_Holl',
'En_Scene_Change',
'En_Zf',
'En_Hata',
'Boss_Dodongo',
'Boss_Goma',
'En_Zl1',
'En_Viewer',
'En_Goma',
'Bg_Pushbox',
'En_Bubble',
'Door_Shutter',
'En_Dodojr',
'En_Bdfire',
'_filler_Magic_filler_',
'En_Boom',
'En_Torch2',
'En_Bili',
'En_Tp',
'_filler_En_OA1_filler_',
'En_St',
'En_Bw',
'En_A_Obj',
'En_Eiyer',
'En_River_Sound',
'En_Horse_Normal',
'En_Ossan',
'Bg_Treemouth',
'Bg_Dodoago',
'Bg_Hidan_Dalm',
'Bg_Hidan_Hrock',
'En_Horse_Ganon',
'Bg_Hidan_Rock',
'Bg_Hidan_Rsekizou',
'Bg_Hidan_Sekizou',
'Bg_Hidan_Sima',
'Bg_Hidan_Syoku',
'En_Xc',
'Bg_Hidan_Curtain',
'Bg_Spot00_Hanebasi',
'En_Mb',
'En_Bombf',
'En_Zl2',
'Bg_Hidan_Fslift',
'En_OE2',
'Bg_Ydan_Hasi',
'Bg_Ydan_Maruta',
'Boss_Ganondrof',
'_filler_En_Npc_filler_',
'En_Am',
'En_Dekubaba',
'En_M_Fire1',
'En_M_Thunder',
'Bg_Ddan_Jd',
'Bg_Breakwall',
'En_Jj',
'En_Horse_Zelda',
'Bg_Ddan_Kd',
'Door_Warp1',
'Obj_Syokudai',
'Item_B_Heart',
'En_Dekunuts',
'Bg_Menkuri_Kaiten',
'Bg_Menkuri_Eye',
'En_Vali',
'Bg_Mizu_Movebg',
'Bg_Mizu_Water',
'Arms_Hook',
'En_fHG',
'Bg_Mori_Hineri',
'En_Bb',
'Bg_Toki_Hikari',
'En_Yukabyun',
'Bg_Toki_Swd',
'En_Fhg_Fire',
'Bg_Mjin',
'Bg_Hidan_Kousi',
'Door_Toki',
'Bg_Hidan_Hamstep',
'En_Bird',
'_filler_En_Stree_filler_',
'_filler_En_Kui_filler_',
'_filler_En_Maruta_filler_',
'_filler_En_Saku_filler_',
'En_Wood02',
'_filler_En_Twood01_filler_',
'_filler_En_Kabu02_filler_',
'_filler_En_Board_filler_',
'_filler_En_Floater_filler_',
'En_Lightbox',
'En_Pu_box',
'_filler_En_Spia_filler_',
'_filler_En_Stoneb_filler_',
'En_Trap',
'En_Arow_Trap',
'En_Vase',
'_filler_Bg_Hidan_Pompfly_filler_',
'En_Ta',
'En_Tk',
'Bg_Mori_Bigst',
'Bg_Mori_Elevator',
'Bg_Mori_Kaitenkabe',
'Bg_Mori_Rakkatenjo',
'En_Vm',
'Demo_Effect',
'Demo_Kankyo',
'Bg_Hidan_Fwbig',
'En_Floormas',
'En_Heishi1',
'En_Rd',
'En_Po_Sisters',
'Bg_Heavy_Block',
'Bg_Po_Event',
'Obj_Mure',
'En_Sw',
'Boss_Fd',
'Object_Kankyo',
'En_Du',
'En_Fd',
'En_Horse_Link_Child',
'Door_Ana',
'Bg_Spot02_Objects',
'Bg_Haka',
'Magic_Wind',
'Magic_Fire',
'_filler_Magic_Ice_filler_',
'En_Ru1',
'Boss_Fd2',
'En_Fd_Fire',
'En_Dh',
'En_Dha',
'En_Rl',
'En_Encount1',
'Demo_Du',
'Demo_Im',
'Demo_Tre_Lgt',
'En_Fw',
'Bg_Vb_Sima',
'En_Vb_Ball',
'Bg_Haka_Megane',
'Bg_Haka_MeganeBG',
'Bg_Haka_Ship',
'Bg_Haka_Sgami',
'_filler_Bg_Haka_Kumo_filler_',
'En_Heishi2',
'En_Encount2',
'En_Fire_Rock',
'En_Brob',
'Mir_Ray',
'Bg_Spot09_Obj',
'Bg_Spot18_Obj',
'Boss_Va',
'Bg_Haka_Tubo',
'Bg_Haka_Trap',
'Bg_Haka_Huta',
'Bg_Haka_Zou',
'Bg_Spot17_Funen',
'En_Syateki_Itm',
'En_Syateki_Man',
'En_Tana',
'En_Nb',
'Boss_Mo',
'En_Sb',
'En_Bigokuta',
'En_Karebaba',
'Bg_Bdan_Objects',
'Demo_Sa',
'Demo_Go',
'En_In',
'En_Tr',
'Bg_Spot16_Bombstone',
'_filler_En_Npc2_filler_',
'Bg_Hidan_Kowarerukabe',
'Bg_Bombwall',
'Bg_Spot08_Iceblock',
'En_Ru2',
'Obj_Dekujr',
'Bg_Mizu_Uzu',
'Bg_Spot06_Objects',
'Bg_Ice_Objects',
'Bg_Haka_Water',
'_filler_En_Npc3_filler_',
'En_Ma2',
'En_Bom_Chu',
'En_Horse_Game_Check',
'Boss_Tw',
'En_Rr',
'En_Ba',
'En_Bx',
'En_Anubice',
'En_Anubice_Fire',
'Bg_Mori_Hashigo',
'Bg_Mori_Hashira4',
'Bg_Mori_Idomizu',
'Bg_Spot16_Doughnut',
'Bg_Bdan_Switch',
'En_Ma1',
'Boss_Ganon',
'Boss_Sst',
'_filler_Boss_Goma2_filler_',
'_filler_En_Stk_filler_',
'En_Ny',
'En_Fr',
'Item_Shield',
'Bg_Ice_Shelter',
'En_Ice_Hono',
'Item_Ocarina',
'_filler_Magic_Light_filler_',
'_filler_Magic_Soul_filler_',
'Magic_Dark',
'Demo_6K',
'En_Anubice_Tag',
'Bg_Haka_Gate',
'Bg_Spot15_Saku',
'Bg_Jya_Goroiwa',
'Bg_Jya_Zurerukabe',
'_filler_Bg_Jya_Sutarukage_filler_',
'Bg_Jya_Cobra',
'Bg_Jya_Kanaami',
'Fishing',
'Obj_Oshihiki',
'Bg_Gate_Shutter',
'Eff_Dust',
'Bg_Spot01_Fusya',
'Bg_Spot01_Idohashira',
'Bg_Spot01_Idomizu',
'Bg_Po_Syokudai',
'Bg_Ganon_Otyuka',
'Bg_Spot15_Rrbox',
'Bg_Umajump',
'_filler_Arrow_Dark_filler_',
'Arrow_Fire',
'Arrow_Ice',
'Arrow_Light',
'_filler_Arrow_Soul_filler_',
'_filler_Arrow_Wind_filler_',
'Item_Etcetera',
'Obj_Kibako',
'Obj_Tsubo',
'En_Wonder_Item',
'En_Ik',
'Demo_Ik',
'En_Skj',
'En_Skjneedle',
'En_G_Switch',
'Demo_Ext',
'Demo_Shd',
'En_Dns',
'Elf_Msg',
'En_Honotrap',
'En_Tubo_Trap',
'Obj_Ice_Poly',
'Bg_Spot03_Taki',
'Bg_Spot07_Taki',
'En_Fz',
'En_Po_Relay',
'Bg_Relay_Objects',
'En_Diving_Game',
'En_Kusa',
'Obj_Bean',
'Obj_Bombiwa',
'_filler_Obj_Breakbox_filler_',
'_filler_Obj_Hahen_filler_',
'Obj_Switch',
'Obj_Elevator',
'Obj_Lift',
'Obj_Hsblock',
'En_Okarina_Tag',
'En_Yabusame_Mark',
'En_Goroiwa',
'En_Ex_Ruppy',
'En_Toryo',
'En_Daiku',
'_filler_En_Stopge_filler_',
'En_Nwc',
'En_Blkobj',
'Item_Inbox',
'En_Ge1',
'Obj_Blockstop',
'En_Sda',
'En_Clear_Tag',
'En_Niw_Lady',
'En_Gm',
'En_Ms',
'En_Hs',
'Bg_Ingate',
'En_Kanban',
'En_Heishi3',
'En_Syateki_Niw',
'En_Attack_Niw',
'Bg_Spot01_Idosoko',
'En_Sa',
'En_Wonder_Talk',
'Bg_Gjyo_Bridge',
'En_Ds',
'En_Mk',
'En_Bom_Bowl_Man',
'En_Bom_Bowl_Pit',
'En_Owl',
'En_Ishi',
'Obj_Hana',
'Obj_Lightswitch',
'Obj_Mure2',
'En_Go',
'En_Fu',
'_filler_En_Nc_filler_',
'En_Changer',
'Bg_Jya_Megami',
'Bg_Jya_Lift',
'Bg_Jya_Bigmirror',
'Bg_Jya_Bombchuiwa',
'Bg_Jya_Amishutter',
'Bg_Jya_Bombiwa',
'Bg_Spot18_Basket',
'_filler_En_Warp_Box_filler_',
'En_Ganon_Organ',
'En_Siofuki',
'En_Stream',
'_filler_En_Zl22_filler_',
'En_Mm',
'En_Ko',
'En_Kz',
'En_Weather_Tag',
'Bg_Sst_Floor',
'En_Ani',
'En_Ex_Item',
'Bg_Jya_Ironobj',
'En_Js',
'En_Jsjutan',
'En_Cs',
'En_Md',
'En_Hy',
'En_Ganon_Mant',
'En_Okarina_Effect',
'En_Mag',
'Door_Gerudo',
'Elf_Msg2',
'Demo_Gt',
'En_Po_Field',
'Efc_Erupc',
'Bg_Zg',
'En_Heishi4',
'En_Zl3',
'Boss_Ganon2',
'En_Kakasi',
'En_Takara_Man',
'Obj_Makeoshihiki',
'Oceff_Spot',
'End_Title',
'_filler_En_Mother_filler_',
'En_Torch',
'Demo_Ec',
'Shot_Sun',
'En_Dy_Extra',
'En_Wonder_Talk2',
'En_Ge2',
'Obj_Roomtimer',
'En_Ssh',
'En_Sth',
'Oceff_Wipe',
'Oceff_Storm',
'En_Weiyer',
'Bg_Spot05_Soko',
'Bg_Jya_1flift',
'Bg_Jya_Haheniron',
'Bg_Spot12_Gate',
'Bg_Spot12_Saku',
'En_Hintnuts',
'En_Nutsball',
'Bg_Spot00_Break',
'En_Shopnuts',
'En_It',
'En_GeldB',
'Oceff_Wipe2',
'Oceff_Wipe3',
'En_Niw_Girl',
'En_Dog',
'En_Si',
'Bg_Spot01_Objects2',
'Obj_Comb',
'Bg_Spot11_Bakudankabe',
'Obj_Kibako2',
'En_Dnt_Demo',
'En_Dnt_Jiji',
'En_Dnt_Nomal',
'En_Guest',
'Bg_Bom_Guard',
'En_Hs2',
'Demo_Kekkai',
'Bg_Spot08_Bakudankabe',
'Bg_Spot17_Bakudankabe',
'_filler_Bg_Mizu_Switch_filler_',
'Obj_Mure3',
'En_Tg',
'En_Mu',
'En_Go2',
'En_Wf',
'En_Skb',
'Demo_Gj',
'Demo_Geff',
'Bg_Gnd_Firemeiro',
'Bg_Gnd_Darkmeiro',
'Bg_Gnd_Soulmeiro',
'Bg_Gnd_Nisekabe',
'Bg_Gnd_Iceblock',
'En_Gb',
'En_Gs',
'Bg_Mizu_Bwall',
'Bg_Mizu_Shutter',
'En_Daiku_Kakariko',
'Bg_Bowl_Wall',
'En_Wall_Tubo',
'En_Po_Desert',
'En_Crow',
'Door_Killer',
'Bg_Spot11_Oasis',
'Bg_Spot18_Futa',
'Bg_Spot18_Shutter',
'En_Ma3',
'En_Cow',
'Bg_Ice_Turara',
'Bg_Ice_Shutter',
'En_Kakasi2',
'En_Kakasi3',
'Oceff_Wipe4',
'En_Eg',
'Bg_Menkuri_Nisekabe',
'En_Zo',
'Obj_Makekinsuta',
'En_Ge3',
'Obj_Timeblock',
'Obj_Hamishi',
'En_Zl4',
'En_Mm2',
'Bg_Jya_Block',
'Obj_Warp2block',
'Bg_Ydan_X???',
'Boss_Ganon_(Demo/Down)',
'En_Hintstone',
'Bg_Mizu_Q???',
]

import win32com.client
import win32con
import win32gui
import win32api
import win32console
from subprocess import Popen, PIPE, CREATE_NO_WINDOW
import time
import os
import win32api
import signal
import random
import ctypes
from datetime import datetime

def gdbStop():
    # surprisingly difficult to do this programatically, just use this tool
    Popen(['windows-kill.exe','-SIGINT',str(gdb_pid)], creationflags = CREATE_NO_WINDOW)

def gdb(command):
    command += '\n'
    gdb_process.stdin.write(command.encode('ascii'))
    gdb_process.stdin.flush()
    time.sleep(0.1)
    gdb_process.stdout.flush()
    output = os.read(gdb_process.stdout.fileno(),999999).decode('ascii').split(os.linesep)
    #print(output)
    return output

def citraPressKey(key):
    hwndMain = win32gui.FindWindow(None, "Citra | Majora's Mask 3D")
    hwndChild = win32gui.GetWindow(hwndMain, win32con.GW_CHILD)
    win32api.PostMessage(hwndChild, win32con.WM_KEYDOWN, VK_CODE[key], 0)
    
def citraReleaseKey(key):
    hwndMain = win32gui.FindWindow(None, "Citra | Majora's Mask 3D")
    hwndChild = win32gui.GetWindow(hwndMain, win32con.GW_CHILD)
    win32api.PostMessage(hwndChild, win32con.WM_KEYUP, VK_CODE[key], 0)
    
def citraKey(key, dur=0.07):
    time.sleep(0.01)
    citraReleaseKey(key) # shouldn't be needed...
    time.sleep(0.01)
    citraPressKey(key)
    time.sleep(dur)
    citraReleaseKey(key)
    time.sleep(0.01)

Popen([ 'taskkill', '/F', '/IM', citra_path.split('\\')[-1] ], creationflags = CREATE_NO_WINDOW)
Popen([ 'taskkill', '/F', '/IM', gdb_path.split('\\')[-1] ], creationflags = CREATE_NO_WINDOW)

time.sleep(2)

citra_process = Popen([citra_path, oot3d_path])
citra_pid = citra_process.pid
time.sleep(2)
gdb_process = Popen([gdb_path], stdin = PIPE, stdout = PIPE, creationflags = CREATE_NO_WINDOW)
gdb_pid = gdb_process.pid

time.sleep(2)
gdb('target remote :24689')
time.sleep(1)
gdb('continue')

def print_heap():
    addr = 0x98f4000
    gdbStop()
    while addr != 0:
        s = gdb('x/12wx 0x%X'%addr)
        free = int(s[-4].strip().split('\t')[1], 16) >> 16
        blocksize = int(s[-4].strip().split('\t')[2], 16)
        nextaddr = int(s[-4].strip().split('\t')[3], 16)
        prevaddr = int(s[-4].strip().split('\t')[4], 16)

        actorId = int(s[-3].strip().split('\t')[1], 16)%0x10000

        params = int(s[-2].strip().split('\t')[4], 16)#%0x10000

        name = actor_names[actorId] if actorId < len(actor_names) else 'n/a'

        print('header:%08X data:%08X free:%X blocksize:%X next_addr:%X prev_addr:%X - Actor %04X %s (%04X)'%(addr, addr+0x10, free, blocksize, nextaddr, prevaddr, actorId, name, params))
        
        addr = nextaddr
    gdb('continue')
